// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Agashiye",
  category: "Restaurant",
  address: "Ahmedabad, Gujarat, India",
  phone: "+91 79 2550 6946",
  email: "",
  website: "",
  mapUrl: "",
  latitude: "",
  longitude: "",
  rating: "4.5",
  reviewsCount: "3200",
  openingHours: "",
  logo: null,
  images: [],
  description: "Traditional Gujarati thali",
  socials: {},
};

export const aiContent = {
  tagline: "Savor Gujarati Tradition",
  heroDescription: "Experience the authentic taste of Gujarat at Agashiye, where traditional thalis meet modern flair. Our chefs use only the freshest ingredients to craft a culinary journey that will leave you wanting more. From spicy street food to comforting home-style dishes, every bite is a testament to our rich cultural heritage.",
  aboutTitle: "The Story of Agashiye",
  aboutText: "Agashiye is more than just a restaurant - it's a celebration of Gujarati culture and tradition. Our founders, passionate about sharing the unique flavors of their homeland, have curated a menu that showcases the diversity and richness of Gujarati cuisine. With a focus on using locally sourced ingredients and time-honored cooking techniques, we aim to transport your taste buds to the vibrant streets of Gujarat. Our restaurant is a warm and inviting space, designed to make you feel like you're dining with family. Whether you're a foodie, a culture enthusiast, or just looking for a truly unique dining experience, Agashiye is the perfect destination for you.",
  services: [
    { icon: "🍴", title: "Traditional Gujarati Thali", description: "Indulge in our signature thali, featuring a selection of authentic Gujarati dishes, including dal, kadhi, and a variety of vegetables and breads." },
    { icon: "🍲", title: "Street Food Corner", description: "Savor the bold flavors of Gujarati street food, from crispy fritters to spicy chaat items, all made with love and care." },
    { icon: "🍜", title: "Gujarati Sweets", description: "Treat your sweet tooth to our traditional Gujarati desserts, including gulab jamun, jalebi, and shrikhand." },
    { icon: "🍹", title: "Regional Beverages", description: "Quench your thirst with our selection of traditional Gujarati drinks, such as chaas, jal jeera, and masala chai." },
    { icon: "👥", title: "Catering Services", description: "Let us bring the flavors of Gujarat to your special occasion, with our customized catering services for parties and events." },
    { icon: "📦", title: "Takeaway and Delivery", description: "Enjoy your favorite Gujarati dishes from the comfort of your own home, with our convenient takeaway and delivery options." }
  ],
  whyChooseUs: [
    { icon: "👨‍🍳", title: "Experienced Chefs", description: "Our chefs have years of experience in crafting authentic Gujarati cuisine, ensuring that every dish that leaves our kitchen is a testament to our culinary expertise." },
    { icon: "🌾", title: "Fresh and Local Ingredients", description: "We use only the freshest and locally sourced ingredients to create our dishes, guaranteeing that every bite is bursting with flavor and nutrition." },
    { icon: "🏠", title: "Homely Ambiance", description: "Our restaurant is designed to make you feel like you're dining with family, with a warm and inviting atmosphere that will make you want to come back for more." },
    { icon: "👍", title: "Personalized Service", description: "Our staff are dedicated to providing you with personalized service, ensuring that your dining experience is tailored to your needs and preferences." }
  ],
  testimonials: [
    { name: "Rahul Patel", role: "Regular Customer", text: "I've been visiting Agashiye for years, and I'm always impressed by the quality and variety of their dishes. The traditional Gujarati thali is a must-try!", rating: 5 },
    { name: "Priya Mehta", role: "Food Blogger", text: "As a food blogger, I'm always on the lookout for authentic and delicious cuisine. Agashiye's street food corner is a hidden gem, with flavors that will transport you to the streets of Gujarat.", rating: 5 },
    { name: "Kiran Shah", role: "Local Resident", text: "I've tried many Gujarati restaurants in Ahmedabad, but Agashiye stands out for its commitment to using fresh and local ingredients. The service is always friendly and attentive, too.", rating: 5 }
  ],
  portfolio: { categories: [{ name: "Traditional Gujarati Dishes", items: [{ title: "Dal Baati", description: "A classic Gujarati dish made with lentils and wheat bread", icon: "🍴" }, { title: "Kadhi", description: "A creamy yogurt-based curry made with gram flour and spices", icon: "🍲" }] },
    { name: "Street Food Delights", items: [{ title: "Pani Puri", description: "A popular street food snack made with crispy puris and flavored water", icon: "🌮" }, { title: "Samosas", description: "Crispy fried or baked pastries filled with spiced potatoes and peas", icon: "🥟" }] },
    { name: "Gujarati Sweets and Desserts", items: [{ title: "Gulab Jamun", description: "Deep-fried dumplings soaked in a sweet and fragrant syrup", icon: "🍰" }, { title: "Jalebi", description: "Crispy fried batter coils soaked in a sweet syrup", icon: "🍭" }] },
    { name: "Regional Beverages", items: [{ title: "Chaas", description: "A refreshing yogurt-based drink flavored with spices and herbs", icon: "🥛" }, { title: "Jal Jeera", description: "A spicy and tangy cumin-flavored drink", icon: "🌶" }] }] },
  pricing: { description: "Affordable prices for authentic Gujarati cuisine", packages: [{ name: "Basic Thali", price: "₹200", period: "per person", description: "Includes dal, kadhi, rice, roti, and vegetables", features: ["Dal", "Kadhi", "Rice", "Roti", "Vegetables"], popular: false, cta: "Book Now" },
    { name: "Deluxe Thali", price: "₹350", period: "per person", description: "Includes dal, kadhi, rice, roti, vegetables, and a dessert", features: ["Dal", "Kadhi", "Rice", "Roti", "Vegetables", "Dessert"], popular: true, cta: "Book Now" },
    { name: "Premium Thali", price: "₹500", period: "per person", description: "Includes dal, kadhi, rice, roti, vegetables, dessert, and a beverage", features: ["Dal", "Kadhi", "Rice", "Roti", "Vegetables", "Dessert", "Beverage"], popular: false, cta: "Book Now" }] },
  faq: { items: [{ question: "What is the average price of a meal at Agashiye?", answer: "The average price of a meal at Agashiye ranges from ₹200 to ₹500 per person, depending on the package and services chosen." },
    { question: "Do you offer any discounts or promotions?", answer: "Yes, we offer discounts and promotions from time to time, so be sure to check our website or social media channels for the latest deals." },
    { question: "Can I customize my meal to suit my dietary preferences?", answer: "Yes, we offer a range of options to suit different dietary preferences, including vegetarian, vegan, and gluten-free. Please inform our staff of your requirements when you place your order." },
    { question: "Do you have a takeaway or delivery service?", answer: "Yes, we offer takeaway and delivery services for your convenience. You can place your order online or by phone, and we will deliver it to your doorstep." },
    { question: "Can I book a table in advance?", answer: "Yes, we recommend booking a table in advance to avoid waiting, especially on weekends or during peak hours. You can book a table online or by phone." },
    { question: "What are your business hours?", answer: "Our business hours are from 11am to 11pm, 7 days a week. However, please note that our hours may vary during holidays or special events, so it's always best to check our website or social media channels for the latest information." }] },
  booking: { title: "Reserve Your Table Today", description: "Don't wait - book your table now and experience the authentic taste of Gujarat at Agashiye. Our friendly staff will ensure that you have a memorable dining experience." },
  ctaTitle: "Taste the Tradition",
  ctaDescription: "Experience the authentic flavors of Gujarat at Agashiye. Book your table now and discover why we're the top choice for traditional Gujarati cuisine in Ahmedabad.",
  ctaButtonText: "Book Your Table",
  metaDescription: "Agashiye: Authentic Gujarati Cuisine in Ahmedabad",
};

export const siteConfig = {
  layout: "default",
  theme: "warm",
  sections: ["about", "services", "portfolio", "gallery", "pricing", "testimonials", "faq", "booking", "contact"],
};
